import type { Ticket, TicketType, TicketPriority, TicketStatus } from './store'

/**
 * CORE-01I: DEMO BUSINESS SCENARIOS
 * 50 realistic ITSM tickets with rich details for enterprise service desk
 */

export function getEnhancedDemoTickets(): Ticket[] {
  const now = Date.now()
  
  return [
    // CRITICAL INCIDENTS (5)
    {
      id: 'INC-1001',
      title: 'Production Database Connection Timeout',
      description: 'Critical production database becoming unresponsive. Multiple application failures reported. Affecting 150+ users across Finance department.',
      type: 'incident' as TicketType,
      priority: 'critical' as TicketPriority,
      status: 'in-progress' as TicketStatus,
      createdBy: 'customer1',
      createdAt: new Date(now - 8 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 45 * 60 * 1000).toISOString(),
      assignedTo: 'agent5',
      category: 'Infrastructure',
      tags: ['database', 'production', 'escalated'],
      slaStatus: 'at-risk',
      csatScore: 0,
      comments: [
        { userId: 'customer1', text: 'Users cannot access financial records', createdAt: new Date(now - 7 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent5', text: 'Investigating database connection pool. Looks like connection limit exceeded.', createdAt: new Date(now - 6 * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent5', duration: 1.5, notes: 'Initial triage and diagnostics', createdAt: new Date(now - 6 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent5', duration: 2, notes: 'Escalated to database team, reviewing logs', createdAt: new Date(now - 4 * 60 * 60 * 1000).toISOString() },
      ],
    },
    {
      id: 'INC-1002',
      title: 'Email Gateway Down - All External Communication Blocked',
      description: 'Email gateway completely offline. Cannot send or receive external emails. Marketing and Sales teams severely impacted.',
      type: 'incident' as TicketType,
      priority: 'critical' as TicketPriority,
      status: 'open' as TicketStatus,
      createdBy: 'customer2',
      createdAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent1',
      category: 'Email',
      tags: ['email', 'gateway', 'critical', 'communication'],
      slaStatus: 'breached',
      resolutionNotes: 'Awaiting vendor support response',
      linkedKnowledgeArticles: ['KB-2847'],
    },
    {
      id: 'INC-1003',
      title: 'Network Outage - All Office Connectivity Lost',
      description: 'Complete network outage affecting entire San Francisco office. Internet, VPN, and internal network down.',
      type: 'incident' as TicketType,
      priority: 'critical' as TicketPriority,
      status: 'in-progress' as TicketStatus,
      createdBy: 'manager1',
      createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 30 * 60 * 1000).toISOString(),
      assignedTo: 'agent3',
      category: 'Network',
      tags: ['network', 'outage', 'office'],
      slaStatus: 'breached',
      comments: [
        { userId: 'manager1', text: 'All ~200 users affected. Time-sensitive issue.', createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent3', text: 'Contacted ISP - their equipment failed. Replacement in progress.', createdAt: new Date(now - 90 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent3', duration: 0.75, notes: 'Diagnosed ISP provider issue', createdAt: new Date(now - 90 * 60 * 1000).toISOString() },
      ],
    },
    {
      id: 'INC-1004',
      title: 'Security Incident - Suspicious Login Activity Detected',
      description: 'Multiple failed login attempts detected on admin accounts. Potential security breach. Compliance team notified.',
      type: 'incident' as TicketType,
      priority: 'critical' as TicketPriority,
      status: 'in-progress' as TicketStatus,
      createdBy: 'security-team',
      createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 1 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent5',
      category: 'Security',
      tags: ['security', 'breach', 'critical'],
      slaStatus: 'compliant' as const,
      comments: [
        { userId: 'security-team', text: 'Detected 500+ failed attempts from 3 countries', createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent5', text: 'Resetting credentials for affected accounts', createdAt: new Date(now - 1 * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent5', duration: 2.5, notes: 'Forensic analysis, credential reset, MFA enforcement', createdAt: new Date(now - 1 * 60 * 60 * 1000).toISOString() },
      ],
    },
    {
      id: 'INC-1005',
      title: 'Application Server Crash - Recurring Memory Leak',
      description: 'Production application server crashing every 4 hours. Memory usage degrading rapidly. Causes customer portal downtime.',
      type: 'incident' as TicketType,
      priority: 'critical' as TicketPriority,
      status: 'pending' as TicketStatus,
      createdBy: 'customer3',
      createdAt: new Date(now - 24 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 12 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent4',
      category: 'Software',
      tags: ['application', 'memory-leak', 'production'],
      slaStatus: 'at-risk',
      comments: [
        { userId: 'customer3', text: 'Customer portal down for 2 hours. Need permanent fix.', createdAt: new Date(now - 24 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent4', text: 'Engaged development team. Investigating code changes from last deploy.', createdAt: new Date(now - 20 * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent4', duration: 3.5, notes: 'Memory profiling, log analysis, dev team coordination', createdAt: new Date(now - 12 * 60 * 60 * 1000).toISOString() },
      ],
      resolutionNotes: 'Awaiting development team code review. Temporary restart schedule in place.',
      linkedKnowledgeArticles: ['KB-1823', 'KB-3094'],
    },

    // HIGH PRIORITY (12)
    {
      id: 'INC-1006',
      title: 'VPN Not Working - Remote Users Disconnected',
      description: 'VPN connection failing for 50+ remote users. Authentication timeouts occurring.',
      type: 'incident',
      priority: 'high' as TicketPriority,
      status: 'in-progress' as TicketStatus,
      createdBy: 'customer4',
      createdAt: new Date(now - 7 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent2',
      category: 'Network',
      tags: ['vpn', 'remote', 'authentication'],
      slaStatus: 'compliant' as const,
      csatScore: 0,
      comments: [
        { userId: 'customer4', text: 'Remote team cannot work', createdAt: new Date(now - 7 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent2', text: 'Restarted VPN concentrator. Testing with users now.', createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent2', duration: 1.5, notes: 'VPN diagnostics and service restart', createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString() },
      ],
      linkedKnowledgeArticles: ['KB-4521'],
    },
    {
      id: 'INC-1007',
      title: 'Shared Drive Access Restricted - Team Cannot Access Files',
      description: 'Finance team unable to access shared drive containing Q3 reports. Permission error when accessing \\\\server\\shared\\finance',
      type: 'incident',
      priority: 'high' as TicketPriority,
      status: 'in-progress' as TicketStatus,
      createdBy: 'customer5',
      createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 1 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent3',
      category: 'Access',
      tags: ['permissions', 'shared-drive', 'access'],
      slaStatus: 'compliant' as const,
      comments: [
        { userId: 'customer5', text: 'Error: Access Denied. Need immediate access to quarterly reports.', createdAt: new Date(now - 5 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent3', text: 'Checked Active Directory. Found corrupted ACL. Rebuilding permissions.', createdAt: new Date(now - 1 * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent3', duration: 2, notes: 'Permission troubleshooting and ACL repair', createdAt: new Date(now - 1 * 60 * 60 * 1000).toISOString() },
      ],
      linkedKnowledgeArticles: ['KB-5234'],
    },
    {
      id: 'INC-1008',
      title: 'Outlook PST File Corruption - Email Access Lost',
      description: 'User Outlook PST file corrupted. Cannot access 5 years of email history. Inbox shows 0 items.',
      type: 'incident',
      priority: 'high' as TicketPriority,
      status: 'pending' as TicketStatus,
      createdBy: 'customer6',
      createdAt: new Date(now - 12 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent1',
      category: 'Email',
      tags: ['outlook', 'pst', 'data-recovery'],
      slaStatus: 'at-risk',
      comments: [
        { userId: 'customer6', text: 'Critical! Years of client communications lost!', createdAt: new Date(now - 12 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent1', text: 'Attempting PST repair using SCANPST.EXE', createdAt: new Date(now - 10 * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent1', duration: 2.5, notes: 'PST file repair attempt and backup recovery', createdAt: new Date(now - 10 * 60 * 60 * 1000).toISOString() },
      ],
      resolutionNotes: 'Recovery in progress. User awaiting restoration confirmation.',
    },
    {
      id: 'REQ-2001',
      title: 'New User Access Required - Onboarding',
      description: 'New executive hire needs immediate access to all systems. Mailbox, AD account, network access, and application licenses.',
      type: 'request' as TicketType,
      priority: 'high' as TicketPriority,
      status: 'in-progress' as TicketStatus,
      createdBy: 'hr-team',
      createdAt: new Date(now - 6 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 2 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent4',
      category: 'Access',
      tags: ['onboarding', 'new-user', 'high-priority'],
      slaStatus: 'compliant' as const,
      comments: [
        { userId: 'hr-team', text: 'Executive starts today. Urgent onboarding needed.', createdAt: new Date(now - 6 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent4', text: 'Created AD account, mailbox, and provisioned licenses', createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent4', duration: 3.5, notes: 'Complete user provisioning setup', createdAt: new Date(now - 2 * 60 * 60 * 1000).toISOString() },
      ],
      resolutionNotes: 'Account ready. User notified with credentials and onboarding docs.',
      linkedKnowledgeArticles: ['KB-1200', 'KB-1201'],
    },
    {
      id: 'INC-1009',
      title: 'Printer Driver Installation Failing on Windows Updates',
      description: 'After Windows Update, network printer driver not loading. Users cannot print. Error code 0x80004005.',
      type: 'incident',
      priority: 'high' as TicketPriority,
      status: 'open' as TicketStatus,
      createdBy: 'customer7',
      createdAt: new Date(now - 4 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 4 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent2',
      category: 'Hardware',
      tags: ['printer', 'driver', 'windows-update'],
      slaStatus: 'compliant' as const,
      comments: [
        { userId: 'customer7', text: 'Printer broken after Windows Update. Everyone affected.', createdAt: new Date(now - 4 * 60 * 60 * 1000).toISOString() },
      ],
      linkedKnowledgeArticles: ['KB-3847', 'KB-2109'],
    },
    {
      id: 'REQ-2002',
      title: 'License Renewal - Adobe Creative Suite Expiring',
      description: 'Adobe Creative Suite licenses expiring in 3 days. 25 licenses need renewal. Budget approved.',
      type: 'request' as TicketType,
      priority: 'high' as TicketPriority,
      status: 'open' as TicketStatus,
      createdBy: 'customer8',
      createdAt: new Date(now - 48 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 48 * 60 * 60 * 1000).toISOString(),
      category: 'Software',
      tags: ['licenses', 'adobe', 'expiring'],
      slaStatus: 'at-risk',
      resolutionNotes: 'Awaiting procurement team to process order',
    },
    {
      id: 'INC-1010',
      title: 'Slow Application Performance - Unresponsive UI',
      description: 'Main CRM application extremely slow. Users report 30+ second response times. Database queries taking too long.',
      type: 'incident',
      priority: 'high' as TicketPriority,
      status: 'in-progress' as TicketStatus,
      createdBy: 'customer9',
      createdAt: new Date(now - 8 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 3 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent5',
      category: 'Software',
      tags: ['performance', 'crm', 'optimization'],
      slaStatus: 'compliant' as const,
      comments: [
        { userId: 'customer9', text: 'Application unusable. Sales team unable to work.', createdAt: new Date(now - 8 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent5', text: 'Running database query optimization. Index rebuild in progress.', createdAt: new Date(now - 3 * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent5', duration: 2.5, notes: 'Database performance analysis and query optimization', createdAt: new Date(now - 3 * 60 * 60 * 1000).toISOString() },
      ],
      linkedKnowledgeArticles: ['KB-4102'],
    },
    {
      id: 'REQ-2003',
      title: 'Laptop Replacement - End of Life Hardware',
      description: 'User laptop hard drive 95% full. Windows Updates failing. Device reaching end of life. Replacement needed.',
      type: 'request' as TicketType,
      priority: 'high' as TicketPriority,
      status: 'pending' as TicketStatus,
      createdBy: 'customer10',
      createdAt: new Date(now - 72 * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 48 * 60 * 60 * 1000).toISOString(),
      assignedTo: 'agent2',
      category: 'Hardware',
      tags: ['hardware', 'laptop', 'replacement', 'eol'],
      slaStatus: 'at-risk',
      comments: [
        { userId: 'customer10', text: 'Device crashing frequently. Need new laptop ASAP.', createdAt: new Date(now - 72 * 60 * 60 * 1000).toISOString() },
        { userId: 'agent2', text: 'Approved. Ordering replacement. ETA 3 business days.', createdAt: new Date(now - 48 * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: 'agent2', duration: 1, notes: 'Hardware assessment and procurement request submitted', createdAt: new Date(now - 48 * 60 * 60 * 1000).toISOString() },
      ],
      resolutionNotes: 'Replacement laptop ordered. Pending delivery.',
      linkedKnowledgeArticles: ['KB-2000'],
    },

    // MEDIUM PRIORITY (20)
    ...Array.from({ length: 20 }, (_, i) => ({
      id: `INC-${1011 + i}`,
      title: [
        'Calendar Permissions Not Working',
        'Laptop Disk Space Low',
        'Password Expires Tomorrow',
        'Mobile Device Sync Issue',
        'Browser Not Loading Websites',
        'Microphone Not Working on Teams',
        'Two Monitor Setup Configuration',
        'Outlook Calendar Sync Delay',
        'Software License Assignment Needed',
        'USB Port Not Responding',
        'Screen Sharing Not Working',
        'Network Drive Mapping Issue',
        'Email Filter Not Working',
        'Authentication Token Expired',
        'Slack Integration Failing',
        'Backup Failed - Disk Space',
        'Certificate Expiring Soon',
        'Legacy System Access Request',
        'Report Generation Taking Hours',
        'Windows Update Installation Hangs'
      ][i],
      description: [
        'Unable to share calendar with colleagues. Permission settings not applying.',
        'C: drive shows 95% usage. Windows Update cannot proceed.',
        'Password reset required before tomorrow. Cannot set new password.',
        'iPhone not syncing emails properly. Exchange sync failing.',
        'Unable to access any external websites. Proxy issue suspected.',
        'Microphone input not detected in Microsoft Teams calls.',
        'Second monitor not recognized after docking station connection.',
        'Calendar events delayed by 2-3 hours. Sync taking too long.',
        'New user needs access to premium software licenses.',
        'External mouse USB not functioning on laptop.',
        'Screen share option greyed out in Teams meetings.',
        'Network drive not mapping after restart. Error 0x00000035.',
        'Important emails being filtered to junk folder incorrectly.',
        'Session keeps timing out after 15 minutes of inactivity.',
        'Slack integration stopped pulling notifications.',
        'Nightly backup failed due to insufficient disk space.',
        'SSL certificate expiring in 30 days. Renewal needed.',
        'User needs access to deprecated reporting system.',
        'Monthly revenue report taking 45 minutes to generate.',
        'Windows Update installation stuck at 34% for 8 hours.'
      ][i],
      type: 'incident' as TicketType,
      priority: 'medium' as TicketPriority,
      status: (['open', 'in-progress', 'pending'][i % 3]) as TicketStatus,
      createdBy: `customer${i + 11}`,
      createdAt: new Date(now - (24 + i * 2) * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - (10 + i) * 60 * 60 * 1000).toISOString(),
      assignedTo: ['agent1', 'agent2', 'agent3', 'agent4', 'agent5'][i % 5],
      category: ['Collaboration', 'Hardware', 'Access', 'Hardware', 'Network', 'Hardware', 'Hardware', 'Email', 'Software', 'Hardware', 'Collaboration', 'Network', 'Email', 'Access', 'Software', 'Infrastructure', 'Infrastructure', 'Software', 'Software', 'Software'][i],
      tags: [['permissions', 'calendar'], ['disk', 'storage'], ['password'], ['mobile', 'sync'], ['network', 'proxy'], ['hardware', 'audio'], ['hardware', 'display'], ['email', 'sync'], ['software', 'license'], ['hardware', 'usb'], ['collaboration', 'teams'], ['network', 'drive'], ['email', 'filter'], ['auth'], ['integration'], ['backup'], ['certificate'], ['legacy'], ['performance'], ['update']][i],
      slaStatus: 'compliant' as const,
      csatScore: 0,
      comments: i % 2 === 0 ? [
        { userId: `customer${i + 11}`, text: 'Issue impacting my work. Need resolution.', createdAt: new Date(now - (20 + i) * 60 * 60 * 1000).toISOString() },
        { userId: ['agent1', 'agent2', 'agent3', 'agent4', 'agent5'][i % 5], text: 'Investigating. Will provide update within 2 hours.', createdAt: new Date(now - (15 + i) * 60 * 60 * 1000).toISOString() },
      ] : [],
      worklogs: i % 3 === 0 ? [
        { userId: ['agent1', 'agent2', 'agent3', 'agent4', 'agent5'][i % 5], duration: 1.5, notes: 'Troubleshooting and diagnostics', createdAt: new Date(now - (12 + i) * 60 * 60 * 1000).toISOString() },
      ] : [],
      linkedKnowledgeArticles: i % 2 === 0 ? [`KB-${5000 + i}`] : [],
    } as Ticket)),

    // LOW PRIORITY (13)
    ...Array.from({ length: 13 }, (_, i) => ({
      id: `REQ-${2004 + i}`,
      title: [
        'General Software Inquiry',
        'System Preferences Update',
        'Document Template Request',
        'Archive Old Project Files',
        'Nice-to-Have Feature Request',
        'Email Signature Update',
        'Desktop Background Change',
        'Font Installation Request',
        'Feedback on Service',
        'Suggestions for Improvement',
        'Configuration Question',
        'Tutorial Request',
        'General Inquiry'
      ][i],
      description: [
        'General question about available software.',
        'Request to update system regional settings.',
        'Need access to company document templates.',
        'Old project files need to be archived to storage.',
        'Would be nice to have this feature in the future.',
        'Requesting signature line update in email.',
        'Can I change my desktop background',
        'Want to install custom fonts on workstation.',
        'Wanted to give feedback on IT service quality.',
        'Have some suggestions for service improvement.',
        'Question about system configuration.',
        'Looking for tutorial on a feature.',
        'General inquiry about IT services'
      ][i],
      type: 'request' as TicketType,
      priority: 'low' as TicketPriority,
      status: (['open', 'in-progress', 'pending', 'resolved'][i % 4]) as TicketStatus,
      createdBy: `customer${i + 31}`,
      createdAt: new Date(now - (72 + i * 3) * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - (24 + i) * 60 * 60 * 1000).toISOString(),
      assignedTo: i < 10 ? ['agent1', 'agent2', 'agent3', 'agent4', 'agent5'][(i + 1) % 5] : undefined,
      category: ['Software', 'System', 'Documentation', 'Storage', 'Enhancement', 'Email', 'Personalization', 'Software', 'Feedback', 'Feedback', 'Configuration', 'Training', 'General'][i],
      tags: [['inquiry'], ['settings'], ['templates'], ['archive'], ['enhancement'], ['email'], ['personalization'], ['fonts'], ['feedback'], ['improvement'], ['config'], ['training'], ['inquiry']][i],
      slaStatus: 'compliant' as const,
      csatScore: i < 8 ? 0 : 4,
      resolutionNotes: i >= 10 ? 'Resolved and closed' : undefined,
    } as Ticket)),

    // RESOLVED TICKETS (10)
    ...Array.from({ length: 10 }, (_, i) => ({
      id: `INC-${1031 + i}`,
      title: [
        'Password Reset - Complete',
        'VPN Access Restored',
        'Email Synchronization Fixed',
        'Monitor Replacement Installed',
        'Network Connection Stabilized',
        'Software License Activated',
        'Printer Configuration Complete',
        'Database Backup Completed Successfully',
        'Security Update Applied',
        'Application Performance Optimized'
      ][i],
      description: [
        'User password has been reset and verified.',
        'VPN connectivity restored for all users.',
        'Outlook synchronization issue resolved.',
        'New monitor installed and configured.',
        'Network stability improved with router update.',
        'Software license key activated and working.',
        'Network printer configured on all workstations.',
        'Full backup completed without errors.',
        'Security patches installed successfully.',
        'Database optimization complete. Performance improved 40%.'
      ][i],
      type: 'incident' as TicketType,
      priority: (['critical', 'high', 'medium', 'low'][i % 4]) as TicketPriority,
      status: 'resolved' as TicketStatus,
      createdBy: `customer${i + 44}`,
      createdAt: new Date(now - (120 + i * 8) * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - (96 + i * 6) * 60 * 60 * 1000).toISOString(),
      resolvedAt: new Date(now - (96 + i * 6) * 60 * 60 * 1000).toISOString(),
      assignedTo: ['agent1', 'agent2', 'agent3', 'agent4', 'agent5'][i % 5],
      category: ['Access', 'Network', 'Email', 'Hardware', 'Network', 'Software', 'Hardware', 'Infrastructure', 'Infrastructure', 'Software'][i],
      tags: [['resolved', 'access'], ['resolved', 'vpn'], ['resolved', 'email'], ['resolved', 'hardware'], ['resolved', 'network'], ['resolved', 'license'], ['resolved', 'printer'], ['resolved', 'backup'], ['resolved', 'security'], ['resolved', 'performance']][i],
      slaStatus: 'compliant' as const,
      csatScore: 5,
      resolutionNotes: [
        'User confirmed access working. Ticket resolved.',
        'All users testing VPN successfully.',
        'Outlook sync verified. All emails synced properly.',
        'Monitor operational. User confirmed satisfaction.',
        'Network stability metrics within normal range.',
        'License activated and working across all modules.',
        'All printers responding to print jobs.',
        'No errors detected in backup logs.',
        'All critical security updates installed.',
        'Database query performance improved significantly.'
      ][i],
      comments: [
        { userId: `customer${i + 44}`, text: 'Thank you for the quick resolution!', createdAt: new Date(now - (100 + i * 7) * 60 * 60 * 1000).toISOString() },
        { userId: ['agent1', 'agent2', 'agent3', 'agent4', 'agent5'][i % 5], text: 'Happy to help! Ticket resolved.', createdAt: new Date(now - (96 + i * 6) * 60 * 60 * 1000).toISOString() },
      ],
      worklogs: [
        { userId: ['agent1', 'agent2', 'agent3', 'agent4', 'agent5'][i % 5], duration: 1.5 + i * 0.5, notes: 'Issue resolution and verification', createdAt: new Date(now - (96 + i * 6) * 60 * 60 * 1000).toISOString() },
      ],
      linkedKnowledgeArticles: [`KB-${6000 + i}`],
    } as Ticket)),

    // CLOSED TICKETS (4)
    ...Array.from({ length: 4 }, (_, i) => ({
      id: `INC-${1041 + i}`,
      title: ['Resolved and Archived', 'Duplicate Ticket Closed', 'Old Issue - No Further Action', 'User Follow-up Completed'][i],
      description: ['Issue resolved and archived after user confirmation.', 'Duplicate of ticket INC-1005.', 'No further user response received. Closing.', 'User confirmed issue resolved. Ready to close.'][i],
      type: 'incident' as TicketType,
      priority: 'low' as TicketPriority,
      status: 'closed' as TicketStatus,
      createdBy: `customer${i + 54}`,
      createdAt: new Date(now - (168 + i * 12) * 60 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - (120 + i * 8) * 60 * 60 * 1000).toISOString(),
      resolvedAt: new Date(now - (120 + i * 8) * 60 * 60 * 1000).toISOString(),
      closedAt: new Date(now - (24 + i * 3) * 60 * 60 * 1000).toISOString(),
      assignedTo: ['agent1', 'agent2', 'agent3', 'agent4'][i],
      category: 'Other',
      tags: ['archived', 'closed'],
      slaStatus: 'compliant' as const,
      csatScore: 5,
      resolutionNotes: ['Archived successfully.', 'Merged with primary ticket.', 'No response from user. Closing.', 'User satisfied. Ticket closed.'][i],
    } as Ticket)),

    // UNASSIGNED (2)
    {
      id: 'INC-1045',
      title: 'New Incoming Request - Awaiting Triage',
      description: 'New support request received. Needs initial assessment and assignment.',
      type: 'incident' as TicketType,
      priority: 'medium' as TicketPriority,
      status: 'open' as TicketStatus,
      createdBy: 'customer58',
      createdAt: new Date(now - 45 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 45 * 60 * 1000).toISOString(),
      category: 'Other',
      tags: ['new', 'unassigned'],
      slaStatus: 'compliant' as const,
    } as Ticket,
    {
      id: 'REQ-2017',
      title: 'Unassigned Feature Request - General Inquiry',
      description: 'Feature request received. Pending review and prioritization.',
      type: 'request' as TicketType,
      priority: 'low' as TicketPriority,
      status: 'open' as TicketStatus,
      createdBy: 'customer59',
      createdAt: new Date(now - 15 * 60 * 1000).toISOString(),
      updatedAt: new Date(now - 15 * 60 * 1000).toISOString(),
      category: 'Other',
      tags: ['unassigned', 'feature-request'],
      slaStatus: 'compliant' as const,
    } as Ticket,
  ]
}

